name: Build Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - '*_build'

env:
  REFINERY_CONFIG: postgres://arroyo:arroyo@localhost:5432/arroyo
  REFINERY_VERSION: "0.8.14"
  PROTOC_VERSION: "27.3"
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  PNPM_VERSION: "9.7.1"
  POSTGRES_USER: arroyo
  POSTGRES_PASSWORD: arroyo
  POSTGRES_DB: arroyo
  POSTGRES_HOST: localhost

jobs:
  linux:
    strategy:
      fail-fast: true
      matrix:
        config:
          - { runner: ubuntu-latest, build_target: x86_64-unknown-linux-gnu, protoc: linux-x86_64, artifact: linux-x86_64 }
          - { runner: ubuntu-latest, build_target: aarch64-unknown-linux-gnu, protoc: linux-x86_64, artifact: linux-aarch64 }
    runs-on: ${{ matrix.config.runner }}
    services:
      postgres:
        image: postgres:14.13-alpine3.20
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Setup conditional aarch64 cross-compilation
        if: matrix.config.build_target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
          echo "PYO3_CROSS_PYTHON_VERSION=${{ env.PYTHON_VERSION }}" >> $GITHUB_ENV

      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.build_target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.build_target }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: echo "PYO3_PYTHON=${{ env.pythonLocation }}/bin/python3" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Install protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.config.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          cargo build --features python --release --package arroyo --target ${{ matrix.config.build_target }}
          cp target/${{ matrix.config.build_target }}/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo --target ${{ matrix.config.build_target }}
          cp target/${{ matrix.config.build_target }}/release/arroyo artifacts/arroyo

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.config.artifact }}
          path: artifacts/*
          if-no-files-found: error

  macos:
    strategy:
      fail-fast: true
      matrix:
        config:
          - { runner: macos-14, build_target: x86_64-apple-darwin, protoc: osx-x86_64, artifact: macos-x86_64 }
          - { runner: macos-14, build_target: aarch64-apple-darwin, protoc: osx-x86_64, artifact: macos-m1 }
    runs-on: ${{ matrix.config.runner }}
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.build_target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.build_target }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - run: echo "PYO3_PYTHON=${{ env.pythonLocation }}/bin/python3" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Install protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.config.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Install Postgres and prepare DB
        run: |
          brew install postgresql@14 && brew services start postgresql && sleep 10
          psql postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD' SUPERUSER;"
          createdb $POSTGRES_DB

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          cargo build --features python --release --package arroyo --target ${{ matrix.config.build_target }}
          cp target/${{ matrix.config.build_target }}/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo --target ${{ matrix.config.build_target }}
          cp target/${{ matrix.config.build_target }}/release/arroyo artifacts/arroyo

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.config.artifact }}
          path: artifacts/*
          if-no-files-found: error

  windows:
    strategy:
      fail-fast: true
      matrix:
        config:
          - { runner: windows-latest, build_target: x86_64-pc-windows-msvc, protoc: win64, artifact: windows-x86_64 }
          - { runner: windows-latest, build_target: aarch64-pc-windows-msvc, protoc: win64, artifact: windows-aarch64 }
    runs-on: ${{ matrix.config.runner }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.build_target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.build_target }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set PYO3_PYTHON environment variable
        run: echo "PYO3_PYTHON=${{ env.pythonLocation }}\python.exe" >> $env:GITHUB_ENV

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run frontend build
        run: cd webui; pnpm install; pnpm build

      - name: Install protoc compiler and set PROTOC env var
        shell: bash
        run: |
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.config.protoc }}.zip"
          unzip protoc*.zip
          echo "PROTOC=$PWD/bin/protoc.exe" >> $GITHUB_ENV

      - name: Install and start PostgreSQL
        run: |
          choco install postgresql14 --version=14.13 -y --no-progress
          echo "C:\Program Files\PostgreSQL\14\bin" >> $env:GITHUB_PATH
          Start-Process -FilePath "C:\Program Files\PostgreSQL\14\bin\pg_ctl.exe" -ArgumentList "start -D 'C:\ProgramData\PostgreSQL\14\data'" -Wait

      - name: Initialize PostgreSQL Database
        run: |
          Start-Sleep -Seconds 10
          & "psql.exe" -U postgres -c "CREATE USER ${{ env.POSTGRES_USER }} WITH PASSWORD '${{ env.POSTGRES_PASSWORD }}' SUPERUSER;"
          & "createdb.exe" -U postgres ${{ env.POSTGRES_DB }}

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          cargo build --features python --release --package arroyo --target ${{ matrix.config.build_target }}
          Copy-Item "target\${{ matrix.config.build_target }}\release\arroyo.exe" "artifacts\arroyo-python.exe"

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo --target ${{ matrix.config.build_target }}
          Copy-Item "target\${{ matrix.config.build_target }}\release\arroyo.exe" "artifacts\arroyo.exe"

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.config.artifact }}
          path: artifacts/*
          if-no-files-found: error
