name: Build Binaries

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - "*_build"

env:
  # Versions
  REFINERY_VERSION: "0.8.14"
  PROTOC_VERSION: "27.3"
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  PNPM_VERSION: "9.7.1"

  # Postgres related
  REFINERY_CONFIG: postgres://arroyo:arroyo@localhost:5432/arroyo
  POSTGRES_USER: arroyo
  POSTGRES_PASSWORD: arroyo
  POSTGRES_DB: arroyo
  POSTGRES_HOST: localhost

  # Cargo build optimizations
  CARGO_PROFILE_RELEASE_LTO: "thin"
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
  CARGO_PROFILE_RELEASE_STRIP: true

jobs:
  linux:
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: ubuntu-latest
            protoc: linux-x86_64
            artifact: linux-x86_64

          - runner: ubuntu-latest-arm
            protoc: linux-aarch_64
            artifact: linux-arm64
    services:
      postgres:
        image: postgres:14.13-alpine3.20
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.artifact }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js ${{ env.NODE_VERSION }} with caching
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Setup protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          PYO3_PYTHON=${{ env.pythonLocation }}/bin/python cargo build --features python --release --package arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo
          mv target/release/arroyo artifacts/arroyo

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.artifact }}
          path: artifacts/*
          if-no-files-found: error

  macos:
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: macos-latest
            protoc: osx-x86_64
            artifact: macos-x86_64

          # - runner: macos-14-xlarge
          #   protoc: osx-aarch_64
          #   artifact: macos-m1
    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.artifact }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js ${{ env.NODE_VERSION }} with caching
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Setup protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Setup PostgreSQL and prepare DB
        run: |
          brew install postgresql@14 && brew services start postgresql && sleep 10
          psql postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD' SUPERUSER;"
          createdb $POSTGRES_DB

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          PYO3_PYTHON=${{ env.pythonLocation }}/bin/python cargo build --features python --release --package arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.artifact }}
          path: artifacts/*
          if-no-files-found: error

  windows:
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: windows-latest
            build_target: x86_64-pc-windows-gnu
            protoc: win64
            artifact: windows-x86_64
            msys2_packages: >-
              mingw-w64-x86_64-toolchain

          - runner: windows-latest
            build_target: aarch64-pc-windows-gnu
            protoc: win64
            artifact: windows-aarch64
            msys2_packages: >-
              mingw-w64-x86_64-toolchain
              mingw-w64-aarch64-toolchain
    name: ${{ matrix.artifact }} (GNU) build
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup MSYS2 and C Dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: ${{ matrix.msys2_packages }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.build_target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.artifact }}

      - name: ${{ format('Setup Python {0}', env.PYTHON_VERSION) }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set PYO3_PYTHON environment variable
        run: echo "PYO3_PYTHON=${{ env.pythonLocation }}\python.exe" >> $env:GITHUB_ENV

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: ${{ format('Setup Node.js {0} with caching', env.NODE_VERSION) }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Setup protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.protoc }}.zip
          unzip protoc*.zip
          mv bin/protoc.exe /mingw64/bin/

      - name: Setup PostgreSQL
        shell: pwsh
        run: |
          choco install postgresql14 --version=14.13 -y --no-progress
          echo "C:\Program Files\PostgreSQL\14\bin" >> $env:GITHUB_PATH
          Start-Process -FilePath "C:\Program Files\PostgreSQL\14\bin\pg_ctl.exe" -ArgumentList "start -D 'C:\ProgramData\PostgreSQL\14\data'" -Wait

      - name: Prepare PostgreSQL Database
        shell: pwsh
        run: |
          Start-Sleep -Seconds 10
          & "psql.exe" -U postgres -c "CREATE USER ${{ env.POSTGRES_USER }} WITH PASSWORD '${{ env.POSTGRES_PASSWORD }}' SUPERUSER;"
          & "createdb.exe" -U postgres ${{ env.POSTGRES_DB }}

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          cargo build --features python --release --package arroyo --target ${{ matrix.build_target }}
          mv target/${{ matrix.build_target }}/release/arroyo.exe artifacts/arroyo-python.exe

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo --target ${{ matrix.build_target }}
          mv target/${{ matrix.build_target }}/release/arroyo.exe artifacts/arroyo.exe

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.artifact }}
          path: artifacts/*
          if-no-files-found: error
