name: Build Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - '*_build'

env:
  REFINERY_CONFIG: postgres://arroyo:arroyo@localhost:5432/arroyo
  REFINERY_VERSION: "0.8.14"
  PROTOC_VERSION: "27.3"
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  PNPM_VERSION: "9.7.1"
  POSTGRES_USER: arroyo
  POSTGRES_PASSWORD: arroyo
  POSTGRES_DB: arroyo
  POSTGRES_HOST: localhost

jobs:
  linux:
    strategy:
      fail-fast: true
      matrix:
        config:
          - { runner: ubuntu-22.04-32, protoc: linux-x86_64, artifact: linux-x86_64 }
          - { runner: ubuntu-22.04-32-arm, protoc: linux-aarch_64, artifact: linux-aarch64 }
    name: ${{ matrix.config.artifact }} build
    runs-on: ${{ matrix.config.runner }}
    services:
      postgres:
        image: postgres:14.13-alpine3.20
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.config.artifact }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Install protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.config.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          PYO3_PYTHON=${{ env.pythonLocation }}/bin/python cargo build --features python --release --package arroyo
          strip target/release/arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo
          strip target/release/arroyo
          mv target/release/arroyo artifacts/arroyo

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.config.artifact }}
          path: artifacts/*
          if-no-files-found: error

  macos:
    strategy:
      fail-fast: true
      matrix:
        config:
          - { runner: macos-latest, protoc: osx-x86_64, artifact: macos-x86_64 }
          # - { runner: macos-14-xlarge, protoc: osx-aarch_64, artifact: macos-m1 }
    name: ${{ matrix.config.artifact }} build
    runs-on: ${{ matrix.config.runner }}
    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.config.artifact }}

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run frontend build
        run: cd webui && pnpm install && pnpm build

      - name: Install protoc compiler
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ matrix.config.protoc }}.zip
          unzip protoc*.zip
          sudo mv bin/protoc /usr/local/bin

      - name: Install Postgres and prepare DB
        run: |
          brew install postgresql@14 && brew services start postgresql && sleep 10
          psql postgres -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD' SUPERUSER;"
          createdb $POSTGRES_DB

      - name: Run DB migrations
        run: |
          cargo install --debug refinery_cli --version ${{ env.REFINERY_VERSION }}
          refinery migrate -e REFINERY_CONFIG -p crates/arroyo-api/migrations

      - run: mkdir artifacts

      - name: Build Arroyo with Python
        run: |
          PYO3_PYTHON=${{ env.pythonLocation }}/bin/python cargo build --features python --release --package arroyo
          strip target/release/arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Build Arroyo without Python
        run: |
          cargo build --release --package arroyo
          strip target/release/arroyo
          mv target/release/arroyo artifacts/arroyo-python

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: arroyo-${{ matrix.config.artifact }}
          path: artifacts/*
          if-no-files-found: error
