name: CI

on: [push, pull_request]

env:
  # Versions
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"
  PNPM_VERSION: "9.7.1"

  DATABASE_URL: "postgres://arroyo:arroyo@localhost:5432/arroyo"

jobs:
  # Lint stage
  lint-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js ${{ env.NODE_VERSION }} with caching
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: webui/pnpm-lock.yaml

      - name: Run prettier
        working-directory: webui
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
          pnpm check

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Check Formatting
        run: cargo fmt -- --check
